spring:
  application:
    name: RSTech-test
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/rstech
    username: backend_app
    password: dGVzdCByc3RlY2ggZGIgcGFzc3dvcmQNCg==
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # day
  refresh-token:
    expiration: 604800000 # 7 days